apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hello-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Hello is the Schema for the hellos API
      displayName: Hello
      kind: Hello
      name: hellos.app.jxlwqq.github.io
      version: v1alpha1
  description: hello-operator
  displayName: hello-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hello-operator
  links:
  - name: Hello Operator
    url: https://hello-operator.domain
  maintainers:
  - email: jxlwqq@gmail.com
    name: jxlwqq
  maturity: alpha
  provider:
    name: jxlwqq
    url: github.com/jxlwqq
  version: 0.0.0
